openapi: 3.0.0
info:
  title: Projeto Integrador 5º Semestre API (₢ Carlos Oliveira)
  version: 1.0.0
  description: Each user has a profile with the password 123456 and can create, update, and delete products and suppliers. Users can also link products to suppliers using a many-to-many relationship. The API is built with Node.js, Express, and a SQLite database, and is secured with JWT.
  author:
    name: Carlos Oliveira
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: Users
    description: Gerenciamento de login e autenticação dos usuários
  - name: Profiles
    description: Gerenciamento de perfis de usuários
  - name: Products
    description: Gerenciamento de produtos
  - name: Suppliers
    description: Gerenciamento de fornecedores
paths:
  /users/signup:
    post:
      summary: User signup
      tags:
        - Users 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful signup
  /users/login:
    post:
      summary: User login
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
  /users:
    get:
      summary: Get all users
      tags:
        - Users
      responses:
        '200':
          description: Successful response
  /profile:
    get:
      summary: Get all user's profile
      tags:
      - Profiles
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
    post:
        summary: Create a new profile for the user
        tags:
          - Profiles
        security:
          - bearerAuth: []
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                  bio:
                    type: string
                  avatarUrl:
                    type: string
                  birthDate:
                    type: string
                  phone:
                    type: string
                  location:
                    type: string
                  website:
                    type: string
        responses:
            '200':
              description: Successful response
    put:
      summary: Update user's profile
      tags:
        - Profiles
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                 userId:
                    type: string
                 bio:
                    type: string
                 avatarUrl:
                    type: string
                 birthDate:
                    type: string
                 phone:
                    type: string
                 location:
                    type: string
                 website:
                    type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful update
  /profile/{userId}:
    delete:
      summary: Delete user's profile
      tags:
        - Profiles
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: User ID
      responses:
        '200':
          description: Successful deletion
  /products:
    get:
      summary: Get all user's products
      tags:
        - Products
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
  /products/{userId}:  
    post:
      summary: Create a new product for the user
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: User ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Successful product creation
  /products/{productId}:
    get:
      summary: Get a user's product by ID
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
    put:
      summary: Update a user's product by ID
      tags:
        - Products
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                name:
                  type: string
                description:
                  type: string
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful product update
    delete:
      summary: Delete a user's product by ID
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful task deletion
  /suppliers:
    get:
      summary: Get all user's suppliers
      tags:
        - Suppliers 
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
  /suppliers/{userId}:  
    post:
      summary: Create a new supplier for the user
      tags:
        - Suppliers
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                companyName:
                  type: string
                cnpj:
                  type: string
                primaryContactName:
                  type: string
      responses:
        '200':
          description: Successful supplier creation
  /suppliers/{supplierId}:
    get:
      summary: Get a user's supplier by ID
      tags:
        - Suppliers
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: supplierId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
    put:
      summary: Update a user's supplier by ID
      tags:
        - Suppliers
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                companyName:
                  type: string
                cnpj:
                  type: string
                primaryContactName:
                  type: string
      parameters:
        - in: path
          name: supplierId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful supplier update
    delete:
      summary: Delete a user's supplier by ID
      tags:
        - Suppliers
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: supplierId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful supplier deletion
  /suppliers/{supplierId}/products:
    get:
      summary: Get products by supplier ID
      tags:
        - Suppliers
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: supplierId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
  /products/{productId}/suppliers:
    get:
      summary: Get suppliers by product ID
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
  /suppliers/{supplierId}/products/{productId}:
    post:
        summary: Link the product to the supplier
        tags:
        - Suppliers
        security:
          - bearerAuth: []
        parameters:
        - in: path
          name: supplierId
          required: true
          schema:
            type: string
        - in: path
          name: productId
          required: true
          schema:
            type: string
        responses:
          '200':
            description: Product successfully associated with supplier
    delete:
      summary: Unlink the product from the supplier
      tags:
        - Suppliers
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: supplierId
          required: true
          schema:
            type: string
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful supplier deletion
  /products/{productId}/suppliers/{supplierId}:
    post:
        summary: Link the supplier to the product
        tags:
          - Products
        security:
          - bearerAuth: []
        parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
        - in: path
          name: supplierId
          required: true
          schema:
            type: string
        responses:
          '200':
            description: Supplier successfully associated with product
    delete:
          summary: Unlink the supplier from the product
          tags:
            - Products
          security:
            - bearerAuth: []
          parameters:
          - in: path
            name: productId
            required: true
            schema:
              type: string
          - in: path
            name: supplierId
            required: true
            schema:
              type: string
          responses:
            '200':
              description: Successful supplier deletion
